{% set version = "1.4.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reshape2
  version: {{ version|replace("-", "_") }}

source:
  fn: reshape2_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/reshape2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reshape2/reshape2_{{ version }}.tar.gz
  sha256: d88dcf9e2530fa9695fc57d0c78adfc5e361305fe8919fe09410b17da5ca12d8

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-plyr >=1.8.1
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-plyr >=1.8.1
    - r-stringr

test:
  commands:
    - $R -e "library('reshape2')"           # [not win]
    - "\"%R%\" -e \"library('reshape2')\""  # [win]

about:
  home: https://github.com/hadley/reshape
  license: MIT
  license_file: LICENSE
  summary: "Flexibly restructure and aggregate data using just two functions: melt and 'dcast' (or 'acast')."
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - lpantano
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
