appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: XaGcwUhxeUuD2XcPU616oYXatWfjr7HBsyKJtVpmRoQqEK69xsnnMxQSYOx/XCv0p6Jv18W0z6pJKlfzj3hEenoDTPRSXheqHKqPaRSvcmC135t273pS+q5fwguYVC6pRJp3p3uvnIn8Jx9yu6ycV0tKDNvZntfq205OfBGtpUeBi6KaGWog8VjOtMan7xR+fOaKJm4Yh+Bdwmkf/ude0lzBb2Y8DkATeS0nTIQ9krMlet61wc48RPXd/oWzuJMFjBnWVFzi0FqJVsOnbX/jKBtRE+b1IYJMIzmmpTvg42CCRSLHwAwQ4CvP1MPJ5szPKcGvVniSORZE/b++whhF+tuEqCXbeKJ4ox4pMuoyyI27h8UKDsKPBOmrMdGnTKXFb9+j58egEXDvfQ+ONJMfLZyae8edUtAVuikYViYFvbNaznL3S+FpwlN4mwhtc0VG2FQE8ypA1Cf+nRBU35fT+CcOlk37RW5QnZ9x3mEk7Fs87Y05M0GP+7YQYXmfdrajM0AYZFQOymOxaTSRgb1HuR/Zky4/gKMow2Lruumrlt88Zx46F9hvR230Khr2oYnnLAt9QuO7kL5S1fqgu3mKoVLrpOwVOc5KsmLRyyhDKf2+YGpNIxJ2bbPSzvNEveY3c4oXk5d+kACGRh3LGvOX3rWkIt2bnUQam0muvlyHB6M=}
bot:
  automerge: true
